run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofumpt
    - gosimple
    - ineffassign
    - errcheck

issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 50

linters-settings:
  gofumpt:
    module-path: github.com/yourname/pr-manager
